ARG DEPS_IMAGE='docker.pkg.github.com/frankchethaka/monorepo-aws-fargate-github-action-demo/monorepo_deps'
FROM ${DEPS_IMAGE1} as builder

COPY core-module/src core-module/src
COPY web-module/src web-module/src

RUN mvn -B -e clean install -DskipTests=true