# This workflow will create docker image per module and push to GitHub Repo. Once done,
# it will perform deploy to AWS Fargate.
# Flow will perform following.
# Trigger: Push on a branch
# Workflow: Build monorepo dependencies and push to GitHub Repo
#   job 1: Build images
#     1. Checkout the Code
#     2. Update maven settings file with GitHub token
#     3. Build Docker image which will download the dependencies
#     4. Push images to GitHub

on:
  schedule:
    - cron: '10 0 * * *'

name: Build monorepo-aws-fargate-github-action-demo modules and deploy to AWS Fargate
env:
    REGISTRY: docker.pkg.github.com
    REPOSITORY: frankchethaka/monorepo-aws-fargate-github-action-demo
    DEPLOY_ENV: staging

jobs:
  compile_code:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 2
      matrix:
        project_type: [ maven ]
        include:
          - project_type: maven
            DEPS_IMAGE_NAME: monorepo_deps_node
            BUILD_IMAGE_NAME: monorepo_build_node
            DOCKERFILE: Maven-Builder-Dockerfile

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Copy workflow content
        run: |
          cp -rp support/fargate/* ./
          cp -rp support/fargate/.env ./
          cp -rp support/secrets ./
      - name: Decrypt secret files
        run: |
          chmod +x ./.github/scripts/decrypt_secrets.sh
          ./.github/scripts/decrypt_secrets.sh
        shell: bash
        env:
          GITHUB_SECRET_PASSPHRASE: ${{ secrets.CI_GITHUB_RESOURCE_PAT }}
      - name: Load ENV Variables
        uses: falti/dotenv-action@v0.2.5
        id: repo_env
      - name: Compile all modules and push to Docker Repo.
        if: matrix.project_type == 'maven'
        id: build_code
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ env.REPOSITORY }}/${{ matrix.BUILD_IMAGE_NAME }}
          tag: ${{ steps.repo_env.outputs.app_version }}
          registry: ${{ env.REGISTRY }}
          dockerfile: ${{ matrix.DOCKERFILE }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          buildArgs: DEPS_IMAGE="${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ matrix.DEPS_IMAGE_NAME }}:latest"


