# This workflow will download dependencies and cache in monorepo_deps image and push to GitHub Repo.  
# Flow will perform following.
# Trigger: Cron task
# Workflow: Build monorepo dependencies and push to GitHub Repo
#   job 1: Build images
#     1. Checkout the Code
#     2. Update maven settings file with GitHub token
#     3. Build Docker image which will download the dependencies
#     4. Push images to GitHub


on:
  push:
    branches:
      - main

name: Build monorepo-aws-fargate-github-action-demo dependencies

jobs:
  create_deps:
    runs-on: ubuntu-20.04
    env:
      REPO: docker.pkg.github.com/healthwaymedical/cms-core
      REGISTRY: docker.pkg.github.com
      REPOSITORY: monorepo-aws-fargate-github-action-demo
    strategy:
      max-parallel: 2
      matrix:
        project_type: [ maven ]
        include:
          - project_type: maven
            IMAGE_NAME: monorepo_deps_node
            DOCKERFILE: Maven-Deps-Dockerfile

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Copy workflow content
        run: |
          cp -rp support/fargate/* ./
          cp -rp support/fargate/.env ./
          cp -rp support/secrets ./
        shell: bash
      - name: Load ENV Variables
        uses: falti/dotenv-action@v0.2.5
        id: repo_env
      - name:  Run dependency docker image build and push to GitHub Repo
        id: docker_deps
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ env.REPOSITORY }}/${{ matrix.IMAGE_NAME }}
          tag: latest
          registry: ${{ env.REGISTRY }}
          dockerfile: ${{ matrix.DOCKERFILE }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}